alias: Tracker Toogle Bool Ett Home
hide_entity: True
trigger:
  platform: state
  entity_id: device_tracker.ettienne_galaxy_s10
  to: home
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.ettienne_home