alias: Tracker Toogle Bool Kelly Home
hide_entity: True
trigger:
  platform: state
  entity_id: device_tracker.kelly_iphone_xr
  to: home
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.kelly_home