alias: Tracker Toogle Bool Kelly Not Home
hide_entity: True
trigger:
  platform: state
  entity_id: device_tracker.kelly_iphone_xr
  to: not_home
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.kelly_home