alias: Tracker Toogle Bool Ett Not Home
hide_entity: True
trigger:
  platform: state
  entity_id: device_tracker.ettienne_galaxy_s10
  to: not_home
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.ettienne_home