- platform: bayesian
  name: Is_Dark
  prior: 0.5
  probability_threshold: 0.6
  observations:
    - platform: numeric_state
      entity_id: sensor.multisensor_dining_light
      prob_given_true: 0.5
      prob_given_false: 0
      below: 100
  # - platform: numeric_state
  #   entity_id: sensor.multisensor_kitchen_light
  #   prob_given_true: 0.6
  #   prob_given_false: 0.4
  #   below: 50
    - platform: state
      entity_id: sun.sun
      prob_given_true: 1
      prob_given_false: 0.5
      to_state: below_horizon
# - platform: hikvision
#   name: HikVision
#   host: !secret hikvision_host
#   username: !secret hikvision_username
#   password: !secret hikvision_password
