- platform: mqtt
  name: GS_WDS07_1
  state_topic: "rtl_433/events"
  payload_on: "24045-ZZ1Z1X1Z00XX"
  payload_off: "24045-ZZ1Z1X1Z001X"
  value_template: "{{ value_json.id }}-{{ value_json.tristate }}"
  device_class: door
- platform: mqtt
  name: GS_WDS07_2
  state_topic: "rtl_433/events"
  payload_on: "24018-ZZ1Z1Z0X00XX"
  payload_off: "24018-ZZ1Z1Z0X001X"
  value_template: "{{ value_json.id }}-{{ value_json.tristate }}"
  device_class: door
- platform: mqtt
  name: GS_WDS07_3
  state_topic: "rtl_433/events"
  payload_on: "21536-ZZZ00X0000XX"
  payload_off: "21536-ZZZ00X00001X"
  value_template: "{{ value_json.id }}-{{ value_json.tristate }}"
  device_class: door
- platform: bayesian
  name: Is_Dark
  prior: 0.5
  probability_threshold: 0.6
  observations:
    - platform: numeric_state
      entity_id: sensor.multisensor_dining_light
      prob_given_true: 0.5
      below: 100
    - platform: numeric_state
      entity_id: sensor.multisensor_kitchen_light
      prob_given_true: 0.6
      below: 50
    - platform: state
      entity_id: sun.sun
      prob_given_true: 1
      to_state: below_horizon
- platform: mqtt
  name: ESP32_1_Motion
  state_topic: "ESP32-1/Motion"
  payload_on: "true"
  off_delay: 2
  device_class: motion
# - platform: hikvision
#   name: HikVision
#   host: !secret hikvision_host
#   username: !secret hikvision_username
#   password: !secret hikvision_password
