ettienne_home:
  name: Ettienne Home
  icon: mdi:human-handsdown
kelly_home:
  name: Kelly Home
  icon: mdi:human-female
house_guests:
  name: House Guests
  icon: mdi:airplane
home_occupied:
  name: Home Occupied
  icon: mdi:human-male-female
bedtime_routine:
  name: Bedtime Routine
  icon: mdi:bed
lounge_music:
  name: Lounge Music
  icon: mdi:music
lounge_tv_time:
  name: Lounge TV Time
  icon: mdi:tv-classic
off_all_lights:
  name: Off all
  icon: mdi:flash-alert
off_upstairs_lights:
  name: Off upstairs
  icon: mdi:lightbulb
off_downstairs_lights:
  name: Off downstairs
  icon: mdi:lightbulb-outline