ettienne_home:
  name: Ettienne Home
  icon: mdi:human-handsdown
kelly_home:
  name: Kelly Home
  icon: mdi:human-female
house_guests:
  name: House Guests
  icon: mdi:airplane
home_occupied:
  name: Home Occupied
  icon: mdi:human-male-female
bedtime_routine:
  name: Bedtime Routine
  icon: mdi:hotel