- platform: mqtt
  name: "Shelly 1 Study Light"
  state_topic: "shellies/shelly1-689DB5/relay/0"
  command_topic: "shellies/shelly1-689DB5/relay/0/command"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: false
  optimistic: false
- platform: mqtt
  name: "Shelly 2.5 Powder Room Basin Light"
  state_topic: "shellies/shellyswitch25-68E4F3/relay/0"
  command_topic: "shellies/shellyswitch25-68E4F3/relay/0/command"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: false
  optimistic: false
- platform: mqtt
  name: "Shelly 2.5 Stairs Light"
  state_topic: "shellies/shellyswitch25-68E4F3/relay/1"
  command_topic: "shellies/shellyswitch25-68E4F3/relay/1/command"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: false
  optimistic: false
- platform: mqtt
  name: "Shelly 1 Alex Kitchen Light"
  state_topic: "shellies/shelly1-B9D681/relay/0"
  command_topic: "shellies/shelly1-B9D681/relay/0/command"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: false
  optimistic: false
- platform: mqtt
  name: "Shelly 2.5 Rumpus Main Light"
  state_topic: "shellies/shellyswitch25-68688E/relay/0"
  command_topic: "shellies/shellyswitch25-68688E/relay/0/command"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: false
  optimistic: false
- platform: mqtt
  name: "Shelly 2.5 Rumpus Side Light"
  state_topic: "shellies/shellyswitch25-68688E/relay/1"
  command_topic: "shellies/shellyswitch25-68688E/relay/1/command"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: false
  optimistic: false
- platform: mqtt
  name: "Shelly 1 Guest Room Light"
  state_topic: "shellies/shelly1-68C70A/relay/0"
  command_topic: "shellies/shelly1-68C70A/relay/0/command"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: false
  optimistic: false
- platform: mqtt
  name: "Shelly 2.5 Kids Bathroom Light"
  state_topic: "shellies/shellyswitch25-69020F/relay/1"
  command_topic: "shellies/shellyswitch25-69020F/relay/1/command"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: false
  optimistic: false
- platform: mqtt
  name: "Shelly 2.5 Master Bathroom Light"
  state_topic: "shellies/shellyswitch25-6912B9/relay/0"
  command_topic: "shellies/shellyswitch25-6912B9/relay/0/command"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: false
  optimistic: false
- platform: mqtt
  name: "Shelly 1 Master Toilet Light"
  state_topic: "shellies/shelly1-68B50C/relay/0"
  command_topic: "shellies/shelly1-68B50C/relay/0/command"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: false
  optimistic: false
- platform: mqtt
  name: "Shelly 1 Kitchen Light"
  state_topic: "shellies/shelly1-98F4ABF32A31/relay/0"
  command_topic: "shellies/shelly1-98F4ABF32A31/relay/0/command"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: false
  optimistic: false
- platform: mqtt
  name: "Shelly 1 Laundry"
  state_topic: "shellies/shelly1-98F4ABF28AC7/relay/0"
  command_topic: "shellies/shelly1-98F4ABF28AC7/relay/0/command"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: false
  optimistic: false
- platform: mqtt
  schema: template
  name: "Shelly Dimmer Dressing Room"
  state_topic: "shellies/shellydimmer-CFF878/light/0/status"
  state_template: '{% if value_json.ison %} on {% else %} off {% endif %}'
  command_topic: "shellies/shellydimmer-CFF878/light/0/set"
  command_on_template: '{"turn": "on"{% if brightness is defined %}, "brightness": {{(brightness | float * 0.3882 + 1) | round(0)}}{% endif %}}'
  command_off_template: '{"turn": "off"}'
  brightness_template: '{{ (value_json.brightness | float * 2.55) | round(0) }}'
- platform: mqtt
  schema: template
  name: "Shelly Dimmer Ruby Lamp" 
  state_topic: "shellies/shellydimmer-D0AA89/light/0/status"
  state_template: '{% if value_json.ison %} on {% else %} off {% endif %}'
  command_topic: "shellies/shellydimmer-D0AA89/light/0/set"
  command_on_template: '{"turn": "on"{% if brightness is defined %}, "brightness": {{(brightness | float * 0.3882 + 1) | round(0)}}{% endif %}}'
  command_off_template: '{"turn": "off"}'
  brightness_template: '{{ (value_json.brightness | float * 2.55) | round(0) }}'
- platform: switch
  name: Discreet Light
  entity_id: switch.tp_link_2
- platform: switch
  name: Garage Flood Light
  entity_id: switch.tp_link_3