platform: universal
name: Media Centre Universal
children:
  - media_player.onkyo_living_room
  - media_player.living_room_kodi
commands:
  turn_on:
    service: media_player.turn_on
    data:
      entity_id: media_player.sony_bravia_tv
  turn_off:
    service: media_player.turn_off
    data:
      entity_id: media_player.sony_bravia_tv
  volume_up:
    service: script.turn_on
    data:
      entity_id: script.onkyo_volume_up
  volume_down:
    service: script.turn_on
    data:
      entity_id: script.onkyo_volume_down
  volume_mute:
    service: script.turn_on
    data:
      entity_id: script.onkyo_volume_mute
attributes:
  state: media_player.sony_bravia_tv
