- platform: systemmonitor
  resources: 
    - type: memory_use_percent
    - type: disk_use_percent
      arg: /home
    - type: load_1m
    - type: load_5m
    - type: load_15m

- platform: filter
  name: "multisensor_dining_temp_filtered"
  entity_id: sensor.multisensor_dining_temp
  filters:
    - filter: outlier
      window_size: 4
      radius: 2.0
    - filter: lowpass
      time_constant: 10
    - filter: time_simple_moving_average
      window_size: 00:05
      precision: 2

- platform: filter
  name: "door_window_sensor_garage_temp_filtered"
  entity_id: sensor.door_window_sensor_garage_temp
  filters:
    - filter: outlier
      window_size: 4
      radius: 2.0
    - filter: lowpass
      time_constant: 10
    - filter: time_simple_moving_average
      window_size: 00:05
      precision: 2

- platform: filter
  name: "door_window_sensor_stairs_closet_temp_filtered"
  entity_id: sensor.door_window_sensor_stairs_closet_temp
  filters:
    - filter: outlier
      window_size: 4
      radius: 2.0
    - filter: lowpass
      time_constant: 10
    - filter: time_simple_moving_average
      window_size: 00:05
      precision: 2

- platform: filter
  name: "multisensor_kitchen_temp_filtered"
  entity_id: sensor.multisensor_kitchen_temp
  filters:
    - filter: outlier
      window_size: 4
      radius: 2.0
    - filter: lowpass
      time_constant: 10
    - filter: time_simple_moving_average
      window_size: 00:05
      precision: 2

- platform: filter
  name: "multisensor_dining_humidity_filtered"
  entity_id: sensor.multisensor_dining_humidity
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
    - filter: lowpass
      time_constant: 10
      precision: 2

- platform: filter
  name: "door_window_sensor_garage_humidity_filtered"
  entity_id: sensor.door_window_sensor_garage_humidity
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
    - filter: lowpass
      time_constant: 10
      precision: 2

- platform: filter
  name: "door_window_sensor_stairs_closet_humidity_filtered"
  entity_id: sensor.door_window_sensor_stairs_closet_humidity
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
    - filter: lowpass
      time_constant: 10
      precision: 2

- platform: filter
  name: "multisensor_kitchen_humidity_filtered"
  entity_id: sensor.multisensor_kitchen_humidity
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
    - filter: lowpass
      time_constant: 10
      precision: 2

# - platform: unitedenergy
#   username: !secret unitedenergy_username
#   password: !secret unitedenergy_password

- platform: template
  sensors:
    no_lights_on:
      friendly_name: Lights On
      value_template: "{{ states.light|selectattr('state','equalto','on')|selectattr('attributes.tracked_light', 'eq', true)|list|length }}"

- platform: template
  sensors:
    no_external_doors_open:
      friendly_name: External Doors Open
      value_template: "{{ (states.binary_sensor|selectattr('state','equalto','on')|selectattr('attributes.external_door', 'eq', true)|list|length) + (states.sensor|selectattr('state','equalto','255')|selectattr('attributes.external_door', 'eq', true)|list|length)}}"

- platform: mqtt
  name: Hygrometer 1 Humidity
  device:
    manufacturer: Ecowitt
    model: WH51
    identifiers: 01123e
  state_topic: "rtl_433/Fineoffset-WH51/01123e/0/moisture"
  unit_of_measurement: "%"
  value_template: "{{ value }}"

- platform: mqtt
  name: Hygrometer 1 Battery
  device:
    manufacturer: Ecowitt
    model: WH51
    identifiers: 01123e
  state_topic: "rtl_433/Fineoffset-WH51/01123e/0/battery_mV"
  unit_of_measurement: "mV"
  value_template: "{{ value }}"

# Moisture grades display on the flower pot icon:
# Humidity range: 4%~0%： Display 0 grid moisture
# Humidity range: 14%~5%：Display 1 grid moisture
# Humidity range: 24%~15%：Display 2 grids moisture
# Humidity range: 34%~25%：Display 3 grids moisture
# Humidity range: 44%~35%：Display 4 grids moisture
# Humidity range: 54%~45%：Display 5 grids moisture
# Humidity range: 64%~55%：Display 6 grids moisture
# Humidity range: 74%~65%：Display 7 grids moisture
# Humidity range: 84%~75%：Display 8 grids moisture
# Humidity range: 94%~85%：Display 9 grids moisture
# Humidity range: 100%~95%：Display 10 grids moisture