- platform: mqtt
  name: "Wifi OpenGateway 8266"
  state_topic: "home/OpenMQTTGateway/SYStoMQTT"
  unit_of_measurement: 'dB'
  value_template: "{{ value_json.rssi}}"
  availability_topic: "home/OpenMQTTGateway/LWT"
  payload_available: "online"
  payload_not_available: "offline"
  icon: "mdi:wifi"
  json_attributes_topic: "home/OpenMQTTGateway/SYStoMQTT"
  device_class: signal_strength

- platform: mqtt
  name: "OpenGateway input"
  state_topic: "home/OpenMQTTGateway/433toMQTT"
  value_template: "{{ value_json.value}}"
  json_attributes_topic: "home/OpenMQTTGateway/433toMQTT"

- platform: systemmonitor
  resources: 
    - type: memory_use_percent
    - type: disk_use_percent
      arg: /home
    - type: load_1m
    - type: load_5m
    - type: load_15m

- platform: filter
  name: "multisensor_dining_temp_filtered"
  entity_id: sensor.multisensor_dining_temp
  filters:
    - filter: outlier
      window_size: 4
      radius: 2.0
    - filter: lowpass
      time_constant: 10
    - filter: time_simple_moving_average
      window_size: 00:05
      precision: 2

- platform: filter
  name: "door_window_sensor_garage_temp_filtered"
  entity_id: sensor.door_window_sensor_garage_temp
  filters:
    - filter: outlier
      window_size: 4
      radius: 2.0
    - filter: lowpass
      time_constant: 10
    - filter: time_simple_moving_average
      window_size: 00:05
      precision: 2

- platform: filter
  name: "door_window_sensor_stairs_closet_temp_filtered"
  entity_id: sensor.door_window_sensor_stairs_closet_temp
  filters:
    - filter: outlier
      window_size: 4
      radius: 2.0
    - filter: lowpass
      time_constant: 10
    - filter: time_simple_moving_average
      window_size: 00:05
      precision: 2

- platform: filter
  name: "multisensor_kitchen_temp_filtered"
  entity_id: sensor.multisensor_kitchen_temp
  filters:
    - filter: outlier
      window_size: 4
      radius: 2.0
    - filter: lowpass
      time_constant: 10
    - filter: time_simple_moving_average
      window_size: 00:05
      precision: 2

- platform: filter
  name: "multisensor_dining_humidity_filtered"
  entity_id: sensor.multisensor_dining_humidity
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
    - filter: lowpass
      time_constant: 10
      precision: 2

- platform: filter
  name: "door_window_sensor_garage_humidity_filtered"
  entity_id: sensor.door_window_sensor_garage_humidity
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
    - filter: lowpass
      time_constant: 10
      precision: 2

- platform: filter
  name: "door_window_sensor_stairs_closet_humidity_filtered"
  entity_id: sensor.door_window_sensor_stairs_closet_humidity
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
    - filter: lowpass
      time_constant: 10
      precision: 2

- platform: filter
  name: "multisensor_kitchen_humidity_filtered"
  entity_id: sensor.multisensor_kitchen_humidity
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
    - filter: lowpass
      time_constant: 10
      precision: 2

# - platform: unitedenergy
#   username: !secret unitedenergy_username
#   password: !secret unitedenergy_password

- platform: template
  sensors:
    no_lights_on:
      friendly_name: Lights On
      value_template: "{{ states.light|selectattr('state','equalto','on')|selectattr('attributes.tracked_light', 'eq', true)|list|length }}"

- platform: template
  sensors:
    no_external_doors_open:
      friendly_name: External Doors Open
      value_template: "{{ (states.binary_sensor|selectattr('state','equalto','on')|selectattr('attributes.external_door', 'eq', true)|list|length) + (states.sensor|selectattr('state','equalto','255')|selectattr('attributes.external_door', 'eq', true)|list|length)}}"

- platform: mqtt
  name: "ESP32_1_Lux"
  state_topic: "ESP32-1/Lux"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 4095
  unit_of_measurement: "LUX"
  device_class: illuminance