- platform: mqtt
  name: "Study Remote 1"
  state_topic: "home/OpenMQTTGateway/433toMQTT"
  command_topic: "home/OpenMQTTGateway/commands/MQTTto433/PLSL_180/433_1"
  value_template: "{{ value_json.value }}"
  payload_on: "349147087"
  payload_off: "349145024"
  optimistic: false
  retain: true
  icon: mdi:remote
- platform: mqtt
  name: "Study Remote 2"
  state_topic: "home/OpenMQTTGateway/433toMQTT"
  command_topic: "home/OpenMQTTGateway/commands/MQTTto433/PLSL_180/433_1"
  value_template: "{{ value_json.value }}"
  payload_on: "349146056"
  payload_off: "349144004"
  optimistic: false
  retain: true
  icon: mdi:remote
- platform: mqtt
  name: "Study Remote 3"
  state_topic: "home/OpenMQTTGateway/433toMQTT"
  command_topic: "home/OpenMQTTGateway/commands/MQTTto433/PLSL_180/433_1"
  value_template: "{{ value_json.value }}"
  payload_on: "349146572"
  payload_off: "349144514"
  optimistic: false
  retain: true
  icon: mdi:remote
- platform: mqtt
  name: "Study Remote 4"
  state_topic: "home/OpenMQTTGateway/433toMQTT"
  command_topic: "home/OpenMQTTGateway/commands/MQTTto433/PLSL_180/433_1"
  value_template: "{{ value_json.value }}"
  payload_on: "349146830"
  payload_off: "349144769"
  optimistic: false
  retain: true
  icon: mdi:remote
- platform: mqtt
  name: "Study Remote All"
  state_topic: "home/OpenMQTTGateway/433toMQTT"
  command_topic: "home/OpenMQTTGateway/commands/MQTTto433/PLSL_180/433_1"
  value_template: "{{ value_json.value }}"
  payload_on: "349144259"
  payload_off: "349145291"
  optimistic: false
  retain: true
  icon: mdi:remote
- platform: mqtt
  name: "Rumpus Remote A B"
  state_topic: "home/OpenMQTTGateway/433toMQTT"
  command_topic: "home/OpenMQTTGateway/commands/MQTTto433/PLSL_180/433_1"
  value_template: "{{ value_json.value }}"
  payload_on: "2599032"
  payload_off: "2599028"
  optimistic: false
  retain: true
  icon: mdi:remote
- platform: mqtt
  name: "Rumpus Remote C D"
  state_topic: "home/OpenMQTTGateway/433toMQTT"
  command_topic: "home/OpenMQTTGateway/commands/MQTTto433/PLSL_180/433_1"
  value_template: "{{ value_json.value }}"
  payload_on: "2599026"
  payload_off: "2599025"
  optimistic: false
  retain: true
  icon: mdi:remote
- platform: mqtt
  name: "Shelly 2.5 Kids Bathroom Extractor"
  state_topic: "shellies/shellyswitch25-69020F/relay/0"
  command_topic: "shellies/shellyswitch25-69020F/relay/0/command"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: false
  optimistic: false
  icon: mdi:fan
- platform: mqtt
  name: "Shelly 2.5 Master Bathroom Extractor"
  state_topic: "shellies/shellyswitch25-6912B9/relay/1"
  command_topic: "shellies/shellyswitch25-6912B9/relay/1/command"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: false
  optimistic: false
  icon: mdi:fan