entities: 
  - name: Router
    url: !secret tomato_url
    icon: mdi:home-automation
  - name: Portainer
    url: !secret portainer_url
    icon: mdi:home-automation
  - name: Nodered
    url: !secret nodered_url
    icon: mdi:home-automation
  - name: Pihole
    url: !secret pihole_url
    icon: mdi:home-automation