version: "3.6"
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    networks:
      - default
      - traefik_proxy
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer/data:/data
      - ${USERDIR}/docker/shared:/shared
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=false"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:portainer.${DOMAINNAME}"
      - "traefik.port=9000"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=portainer.gous.duckdns.org"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
  homeassistant:
    container_name: homeassistant
    restart: unless-stopped
    image: homeassistant/home-assistant
    devices:
      - "/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave:rmw"
    volumes:
      - ${USERDIR}/docker/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/shared:/shared
    network_mode: host
    ports:
      - "8123:8123"
      - "56700:56700/udp"
    privileged: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - "traefik.enable=false"
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ${USERDIR}/docker/mosquitto/config:/mosquitto/config
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/mosquitto/data/mosquitto-data:/mosquitto/data
      - ${USERDIR}/docker/mosquitto/data/mosquitto-log:/mosquitto/log
    network_mode: host
    ports:
      - "1883:1883"
      - "9001:9001"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  influxdb:
    container_name: influxdb
    image: influxdb:alpine
    ports:
      - "8086:8086"
      - "8083:8083"
    restart: unless-stopped
    volumes:
      - ${USERDIR}/docker/influxdb:/var/lib/influxdb
      - ${USERDIR}/docker/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ${USERDIR}/docker/shared:/shared
    environment:
      INFLUXDB_DB: ${DBNAME}
      INFLUXDB_USER: ${DBUSER}
      INFLUXDB_USER_PASSWORD: ${DBPASS}
      TZ: ${TZ}
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${DBPASS}
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana
      - ${USERDIR}/docker/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ${USERDIR}/docker/shared:/shared
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.frontend.rule=Host:grafana.${DOMAINNAME}"
      - "traefik.port=3000"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=grafana.gous.duckdns.org"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      #- "traefik.frontend.auth.basic.users=${HTTP_USERNAME}:${HTTP_PASSWORD}"
  unifi:
    container_name: unifi
    image: jacobalberty/unifi
    restart: unless-stopped
    network_mode: host
    # networks:
    #   - traefik_proxy
    volumes:
      - ${USERDIR}/docker/unifi/data/lib:/var/lib/unifi
      - ${USERDIR}/docker/unifi/data/log:/var/log/unifi
      - ${USERDIR}/docker/unifi/data/run:/var/run/unifi
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "6789:6789/tcp"
      - "8080:8080/tcp"
      - "8081:8081/tcp"
      - "8880:8880/tcp"
      - "8443:8443/tcp"
      - "8843:8843/tcp"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.tags=frontend"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.admin.backend=unifi"
      - "traefik.admin.frontend.rule=Host:unifi.${DOMAINNAME}"
      - "traefik.admin.port=8443"
      - "traefik.admin.protocol=https"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=unifi.gous.duckdns.org"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
  pihole:
    container_name: pihole
    image: pihole/pihole
    restart: unless-stopped
    ports:
      - "192.168.1.40:53:53/tcp"
      - "192.168.1.40:53:53/udp"
      - "192.168.1.40:67:67/udp"
      - "192.168.1.40:8181:80/tcp"
      - "192.168.1.40:8444:443/tcp"
    environment:
      - TZ=${TZ}
    volumes:
       - ${USERDIR}/docker/pihole/etc:/etc/pihole/
       - ${USERDIR}/docker/pihole/dnsmasq:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    networks:
      - default
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=pihole"
      - "traefik.frontend.rule=Host:pihole.${DOMAINNAME}"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=pihole.gous.duckdns.org"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.basic.users=${HTTP_USERNAME}:${HTTP_PASSWORD}"
  nodered:
    container_name: nodered
    image: nodered/node-red-docker:v8
    depends_on:
      - mosquitto
      - homeassistant
    restart: unless-stopped
    # network_mode: host
    networks:
      - traefik_proxy
    ports:
      - "1880:1880"
    volumes:
      - ${USERDIR}/docker/nodered/data/etc:/data
    environment:
      - user=${PUID}
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nodered"
      - "traefik.frontend.rule=Host:nodered.${DOMAINNAME}"
      - "traefik.port=1880"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=nodered.gous.duckdns.org"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.basic.users=${HTTP_USERNAME}:${HTTP_PASSWORD}"
  traefik:
    hostname: traefik
    image: traefik:latest
    container_name: traefik
    restart: always
    domainname: ${DOMAINNAME}
    networks:
      - default
      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"
      - "8282:8080"
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=traefik.gous.duckdns.org"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.basic.users=${HTTP_USERNAME}:${HTTP_PASSWORD}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${USERDIR}/docker/traefik:/etc/traefik
      - ${USERDIR}/docker/shared:/shared
  watchtower:
    container_name: watchtower
    hostname: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup
volumes:
  grafana-storage:
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
