- id: '1559733993770'
  alias: bool_on_tracker_ettienne_home
  trigger:
  - entity_id: device_tracker.galaxy_s10_2
    platform: state
    to: home
  condition: []
  action:
  - data:
      entity_id: input_boolean.ettienne_home
    service: input_boolean.turn_on
