homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret timezone
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages
  
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
api:
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Discover some devices automatically
discovery:

   

# Text to speech
tts:
  - platform: google_translate

light: !include config/light.yaml
group: !include groups.yaml
script: !include scripts.yaml
sensor: !include config/sensor.yaml
switch: !include config/switch.yaml
binary_sensor: !include config/binary_sensor.yaml
input_boolean: !include config/boolean.yaml
media_player: !include config/media_player.yaml
camera: !include config/camera.yaml
google_assistant: !include config/google_assistant.yaml
shopping_list:

influxdb:
  host: !secret influxdb_host

speedtestdotnet:

panel_custom:
  - name: zwavegraph2
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:access-point-network
    url_path: zwave

pi_hole:
  host: !secret pihole_ip

lifx:
  light:
    - broadcast: 192.168.1.80
    - broadcast: 192.168.1.81
    - broadcast: 192.168.1.82
    - broadcast: 192.168.1.83
    - broadcast: 192.168.1.84
    - broadcast: 192.168.1.85
    - broadcast: 192.168.1.86
    - broadcast: 192.168.1.87
    - broadcast: 192.168.1.88

tplink:
  discovery: false
  switch:
    - host: 192.168.1.44
    #- host: 192.168.1.45
    - host: 192.168.1.48
    - host: 192.168.1.50

notify:
  - platform: discord
    name: discord notifications
    token: !secret discord_bot_token

frontend:
  themes: !include themes.yaml

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 61
  
logger:
  default: warn
  logs:
    homeassistant.components.mqtt.binary_sensor: critical
    homeassistant.components.unitedenergy: debug

