homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

api:
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.20.0.0/24
    - 127.0.0.1
    - ::1
history:   

# Text to speech
tts:
  - platform: google_translate

light: !include config/light.yaml
group: !include groups.yaml
script: !include scripts.yaml
mqtt: !include config/mqtt.yaml
automation: !include automations.yaml
counter:
input_datetime:
input_select:
input_number:
input_button:
schedule:
input_text:
my:
sensor: !include config/sensor.yaml
binary_sensor: !include config/binary_sensor.yaml
input_boolean: !include config/boolean.yaml
media_player: !include config/media_player.yaml
media_source:
camera: !include config/camera.yaml
google_assistant: !include config/google_assistant.yaml
shopping_list:
timer:
# influxdb:
#   host: !secret influxdb_host

shell_command:
   frame_tv_cec_on: !secret frame_tv_cec_on
   frame_tv_cec_off: !secret frame_tv_cec_off

spotcast:
  sp_dc: !secret spotcast_dc
  sp_key: !secret spotcast_key

# notify:
#   - platform: discord
#     name: discord notifications
#     token: !secret discord_bot_token

frontend:
  themes: !include themes.yaml
  
recorder:
  db_url: !secret database_connectionstring

default_config:

logger:
  default: warn
  logs:
    homeassistant.components.mqtt.binary_sensor: critical
    # homeassistant.components.unitedenergy: debug
    # custom_components.bonaire_myclimate: debug
    custom_components.localtuya: debug
    custom_components.localtuya.pytuya: debug