homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

api:
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.18.0.0/24
    - 127.0.0.1
    - ::1

# Discover some devices automatically
discovery:

history:   

# Text to speech
tts:
  - platform: google_translate

light: !include config/light.yaml
group: !include groups.yaml
script: !include scripts.yaml
mqtt: !include config/mqtt.yaml

sensor: !include config/sensor.yaml
binary_sensor: !include config/binary_sensor.yaml
input_boolean: !include config/boolean.yaml
media_player: !include config/media_player.yaml
media_source:
camera: !include config/camera.yaml
google_assistant: !include config/google_assistant.yaml
shopping_list:
timer:
# influxdb:
#   host: !secret influxdb_host

lifx:
  light:
    - broadcast: 192.168.20.70
    - broadcast: 192.168.20.71
    - broadcast: 192.168.20.72
    - broadcast: 192.168.20.73
    - broadcast: 192.168.20.74
    - broadcast: 192.168.20.75

spotcast:
  sp_dc: !secret spotcast_dc
  sp_key: !secret spotcast_key

notify:
  - platform: discord
    name: discord notifications
    token: !secret discord_bot_token

frontend:
  themes: !include themes.yaml
  
recorder:
  db_url: !secret database_connectionstring

logger:
  default: warn
  logs:
    homeassistant.components.mqtt.binary_sensor: critical
    homeassistant.components.unitedenergy: debug
    custom_components.bonaire_myclimate: debug

rainbird:
  - host: 192.168.20.155
    password: !secret rainbird_password
    trigger_time:
      minutes: 6
    zones:
      1:
        friendly_name: Lawn Back North
        trigger_time:
          minutes: 10
      2:
        friendly_name: Lawn Back South
        trigger_time:
          minutes: 10
      3:
        friendly_name: Lawn Back Centre
        trigger_time:
          minutes: 10
      4:
        friendly_name: Veggie Patch
        trigger_time:
          minutes: 6
      5:
        friendly_name: Lawn Front
        trigger_time:
          minutes: 15
      6:
        friendly_name: Drip Front Back Side
        trigger_time:
          minutes: 30