alias: RF Remote Study Light On
hide_entity: True
trigger:
    platform: mqtt
    topic: "home/OpenMQTTGateway/433toMQTT"
condition: 
  condition: template
  value_template: "{{ trigger.payload_json.value == 349147087 }}"
action:
  - service: light.turn_on
    entity_id: light.lifx_study