alias: RF Remote Rumpus Light On
hide_entity: True
trigger:
  platform: mqtt
  topic: "home/OpenMQTTGateway/433toMQTT"
condition: 
  condition: or
  conditions:
  - condition: template
    value_template: "{{ trigger.payload_json.value == 349146572 }}"
  - condition: template
    value_template: "{{ trigger.payload_json.value == 2599032 }}"
action:
  - service: light.turn_on
    entity_id: light.dimmer_rumpus_light_level