alias: Door or Motion Trigger Pantry Light Off
hide_entity: True
trigger:
- platform: state
  entity_id: 
    - binary_sensor.multisensor_kitchen_motion
  to: 'off'
  for:
        minutes: 1
- platform: state
  entity_id: 
    - binary_sensor.door_window_sensor_pantry_open
  to: 'off'        
action:
  - service: light.turn_off
    entity_id: light.lifx_pantry