alias: Door Trigger Stairs Closet Light On
hide_entity: True
trigger:
- platform: state
  entity_id: 
    - sensor.door_window_sensor_stairs_closet_open
  to: '255'
action:
  - service: light.turn_on
    entity_id: light.lifx_stairs_closet