http:   
  routers:
    traefik-local-router:
      entryPoints:
        - "http"
      rule: "Host(`traefik.`)"
      service: intentional-empty-service
      middlewares:
        - traefik-local-redirect
    printer-local-router:
      entryPoints:
        - "http"
      rule: "Host(`printer.`)"
      service: intentional-empty-service
      middlewares:
        - printer-local-redirect
    hass-router:
      entryPoints:
        - "http"
        - "https"
      rule: "Host(`hass.{{env "DOMAINNAME"}}`)"
      service: "hass-service"
      tls:
        certresolver: letsencrypt
      middlewares:
        - secured-no-basic
    octopi-router:
        entryPoints:
            - "http"
            - "https"
        rule: "Host(`octopi.{{env "DOMAINNAME"}}`)"
        service: "octopi-service"
        tls:
            certresolver: letsencrypt
        middlewares:
            - secured

    unifi-router:
        entryPoints:
            - "http"
            - "https"
        rule: "Host(`unifi.{{env "DOMAINNAME"}}`)"
        service: "unifi-service"
        tls:
            certresolver: letsencrypt
        middlewares:
            - extraheaders

    zigbee2mqtt-router:
        entryPoints:
            - "http"
            - "https"
        rule: "Host(`zigbee2mqtt.{{env "DOMAINNAME"}}`)"
        service: "zigbee2mqtt-service"
        tls:
            certresolver: letsencrypt
        middlewares:
            - secured

    teslacert-router:
        entryPoints:
            - "https"
        rule: "Host(`tesla1.{{env "DOMAINNAME"}}`) && Path(`/.well-known/appspecific/{anything:.*}`)"
        service: "teslacert-service"
        tls:
            certresolver: letsencrypt
        middlewares:
            - tesla-cert-rewrite 

    teslaflask-router:
        entryPoints:
            - "https"
        rule: "Host(`tesla1.{{env "DOMAINNAME"}}`)"
        service: "teslaflask-service"
        tls:
            certresolver: letsencrypt

  services:
    intentional-empty-service:
      loadBalancer:
        passHostHeader: false

    hass-service:
      loadBalancer:
        passHostHeader: false
        servers:
        - url: "http://192.168.1.40:8123/"
        
    octopi-service:
        loadBalancer:
            passHostHeader: false
            servers:
            - url: "http://192.168.1.26/"

    unifi-service:
        loadBalancer:
            passHostHeader: true
            healthCheck:
                scheme: https
                port: 8443
            servers:
            - url: "https://192.168.1.40:8443/"

    zigbee2mqtt-service:
        loadBalancer:
            passHostHeader: false
            healthCheck:
                scheme: https
                port: 8080
            servers:
            - url: "https://192.168.1.22:8080/"

    teslacert-service:
        loadBalancer:
            passHostHeader: false
            healthCheck:
                scheme: http
                port: 8123
            servers:
            - url: "http://192.168.1.40:8123/"

    teslaflask-service:
        loadBalancer:
            passHostHeader: false
            healthCheck:
                scheme: http
                port: 8099
            servers:
            - url: "http://192.168.1.40:8099/"

  middlewares:
    traefik-local-redirect: 
      redirectRegex:
        regex: "^http://(.*)/(.*)"
        replacement: "http://192.168.1.40:8282/${2}"
    printer-local-redirect: 
      redirectRegex:
        regex: "^http://(.*)/(.*)"
        replacement: "http://192.168.1.8/${2}"
    httpbasicauth:
      basicAuth:
        usersFile: /shared/.htpasswd
        removeHeader: true
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: false
    secureheaders:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 315360000
    extraheaders: 
        headers:
            referrerPolicy: "no-referrer"
    web-socket-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "http"
          # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          # proxy_set_header  $scheme;
          # proxy_set_header Upgrade $http_upgrade;
          # proxy_set_header Connection "Upgrade";
    tesla-cert-rewrite: 
      replacePathRegex:
        regex: "^/.well-known/appspecific/(.*)"
        replacement: "/local/certs/$1"
    secured:
      chain:
        middlewares:
        - https-redirect
        - httpbasicauth
        - secureheaders
    secured-no-basic:
        chain:
            middlewares:
            - https-redirect
            - web-socket-headers
            - secureheaders