fan:
    - platform: mqtt
      name: "Diffuser"
      availability_topic: "tele/asakuki-diffuser/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
      state_topic: "tele/asakuki-diffuser/STATE"
      state_value_template: "{{ value_json.POWER1 }}"
      command_topic: "cmnd/asakuki-diffuser/POWER1"
      payload_on: "ON"
      payload_off: "OFF"
      percentage_state_topic: "tele/asakuki-diffuser/STATE"
      percentage_value_template: "{{ value_json.POWER3 }}"
      percentage_command_topic: "cmnd/asakuki-diffuser/POWER3"
      speed_range_min: 1
      speed_range_max: 5
      oscillation_state_topic: "stat/asakuki-diffuser/EFFECT"
      oscillation_command_topic: "cmnd/asakuki-diffuser/EVENT"
      oscillation_value_template: "{{ value }}"
      payload_oscillation_on: "rgb_cycle"
      payload_oscillation_off: "color"
      qos: 1
light:
    - platform: mqtt
      name: "Diffuser Lamp"
      command_topic: "cmnd/asakuki-diffuser/EVENT"
      state_topic: "tele/asakuki-diffuser/STATE"
      state_value_template: "{% if value_json.POWER2 == 'ON' %}{% if value_json.POWER5 == 'ON' %}ON{% else %}OFF{% endif %}{% else %}OFF{% endif %}"
      payload_on: "ON"
      payload_off: "OFF"
      brightness_command_topic: "cmnd/asakuki-diffuser/Dimmer"
      brightness_state_topic: "tele/asakuki-diffuser/RESULT"
      brightness_scale: 100
      # brightness_value_template: "{{ value_json.Dimmer }}"
      brightness_value_template: "{% if value_json.TuyaReceived is defined and value_json['TuyaReceived'].DpId == 108 %}{{ value_json['TuyaReceived'].Type3Data[12:14]|int(base=16) }}{% endif %}"
      availability_topic: "tele/asakuki-diffuser/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
      qos: 1
      retain: false
      rgb_command_topic: "cmnd/asakuki-diffuser/tuyasend3"
      rgb_command_template: "{% set brightness = state_attr('light.diffuser_lamp','brightness') | int %}{{ '108,%02x%02x%02x646464' | format(red, green, blue)}}{{ '%02x' | format(brightness) }}"
      rgb_value_template: "{% if value_json.TuyaReceived is defined and value_json['TuyaReceived'].DpId == 108 %}{{ (value_json['TuyaReceived'].Type3Data[0:2]|int(base=16),value_json['TuyaReceived'].Type3Data[2:4]|int(base=16),value_json['TuyaReceived'].Type3Data[4:6]|int(base=16)) | join(',')}}{% endif %}"
      rgb_state_topic: "tele/asakuki-diffuser/RESULT"

binary_sensor:
    - platform: mqtt
      name: "Aromatherapy Water"
      state_topic: "stat/asakuki-diffuser/POWER4"
      payload_on: "ON"
      payload_off: "OFF"
      availability_topic: "tele/asakuki-diffuser/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
      qos: 1
      device_class: problem