light:
    - platform: "mqtt"
      name: "Tradfri Bulb 1"
      state_topic: "zigbee2mqtt/Tradfri Bulb 1"
      availability_topic: "zigbee2mqtt/bridge/state"
      brightness: true
      schema: "json"
      command_topic: "zigbee2mqtt/Tradfri Bulb 1/set"
      brightness_scale: 254
sensor:
    - platform: "mqtt"
      state_topic: "zigbee2mqtt/Tradfri Bulb 1"
      availability_topic: "zigbee2mqtt/bridge/state"
      icon: "mdi:signal"
      unit_of_measurement: "lqi"
      value_template: "{{ value_json.linkquality }}"  
binary_sensor:
    - platform: "mqtt"
      state_topic: "zigbee2mqtt/Tradfri Bulb 1"
      availability_topic: "zigbee2mqtt/bridge/state"
      payload_on: true
      payload_off: false
      value_template: "{{ value_json.update_available}}"